# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitor.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\027mliot.monitor.generatedP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmonitor.proto\"\x0e\n\x0c\x45mptyMessage\"i\n\x14KnownStudentResponse\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x13\n\x0b\x63\x61rd_number\x18\x03 \x01(\t\x12\x15\n\rprofile_photo\x18\x04 \x01(\x0c\"&\n\x0fMonitorResponse\x12\x13\n\x0bis_received\x18\x01 \x01(\x08\"$\n\x10ProximityMessage\x12\x10\n\x08\x64istance\x18\x01 \x01(\x02\"*\n\x14StepDetectionMessage\x12\x12\n\nisDetected\x18\x01 \x01(\x08\"-\n\x16MotionDetectionMessage\x12\x13\n\x0bis_detected\x18\x01 \x01(\x08\x32\x8c\x02\n\x0eMonitorService\x12>\n\x12\x66\x65tchKnownStudents\x12\r.EmptyMessage\x1a\x15.KnownStudentResponse\"\x00\x30\x01\x12;\n\x0eonStepDetected\x12\x15.StepDetectionMessage\x1a\x10.MonitorResponse\"\x00\x12<\n\x13onProximityDetected\x12\x11.ProximityMessage\x1a\x10.MonitorResponse\"\x00\x12?\n\x10onMotionDetected\x12\x17.MotionDetectionMessage\x1a\x10.MonitorResponse\"\x00\x42\x1b\n\x17mliot.monitor.generatedP\x01\x62\x06proto3'
)




_EMPTYMESSAGE = _descriptor.Descriptor(
  name='EmptyMessage',
  full_name='EmptyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=31,
)


_KNOWNSTUDENTRESPONSE = _descriptor.Descriptor(
  name='KnownStudentResponse',
  full_name='KnownStudentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='KnownStudentResponse.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='KnownStudentResponse.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='card_number', full_name='KnownStudentResponse.card_number', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='profile_photo', full_name='KnownStudentResponse.profile_photo', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=138,
)


_MONITORRESPONSE = _descriptor.Descriptor(
  name='MonitorResponse',
  full_name='MonitorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_received', full_name='MonitorResponse.is_received', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=178,
)


_PROXIMITYMESSAGE = _descriptor.Descriptor(
  name='ProximityMessage',
  full_name='ProximityMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='distance', full_name='ProximityMessage.distance', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=216,
)


_STEPDETECTIONMESSAGE = _descriptor.Descriptor(
  name='StepDetectionMessage',
  full_name='StepDetectionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isDetected', full_name='StepDetectionMessage.isDetected', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=260,
)


_MOTIONDETECTIONMESSAGE = _descriptor.Descriptor(
  name='MotionDetectionMessage',
  full_name='MotionDetectionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_detected', full_name='MotionDetectionMessage.is_detected', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=307,
)

DESCRIPTOR.message_types_by_name['EmptyMessage'] = _EMPTYMESSAGE
DESCRIPTOR.message_types_by_name['KnownStudentResponse'] = _KNOWNSTUDENTRESPONSE
DESCRIPTOR.message_types_by_name['MonitorResponse'] = _MONITORRESPONSE
DESCRIPTOR.message_types_by_name['ProximityMessage'] = _PROXIMITYMESSAGE
DESCRIPTOR.message_types_by_name['StepDetectionMessage'] = _STEPDETECTIONMESSAGE
DESCRIPTOR.message_types_by_name['MotionDetectionMessage'] = _MOTIONDETECTIONMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMessage)
  })
_sym_db.RegisterMessage(EmptyMessage)

KnownStudentResponse = _reflection.GeneratedProtocolMessageType('KnownStudentResponse', (_message.Message,), {
  'DESCRIPTOR' : _KNOWNSTUDENTRESPONSE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:KnownStudentResponse)
  })
_sym_db.RegisterMessage(KnownStudentResponse)

MonitorResponse = _reflection.GeneratedProtocolMessageType('MonitorResponse', (_message.Message,), {
  'DESCRIPTOR' : _MONITORRESPONSE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:MonitorResponse)
  })
_sym_db.RegisterMessage(MonitorResponse)

ProximityMessage = _reflection.GeneratedProtocolMessageType('ProximityMessage', (_message.Message,), {
  'DESCRIPTOR' : _PROXIMITYMESSAGE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:ProximityMessage)
  })
_sym_db.RegisterMessage(ProximityMessage)

StepDetectionMessage = _reflection.GeneratedProtocolMessageType('StepDetectionMessage', (_message.Message,), {
  'DESCRIPTOR' : _STEPDETECTIONMESSAGE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:StepDetectionMessage)
  })
_sym_db.RegisterMessage(StepDetectionMessage)

MotionDetectionMessage = _reflection.GeneratedProtocolMessageType('MotionDetectionMessage', (_message.Message,), {
  'DESCRIPTOR' : _MOTIONDETECTIONMESSAGE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:MotionDetectionMessage)
  })
_sym_db.RegisterMessage(MotionDetectionMessage)


DESCRIPTOR._options = None

_MONITORSERVICE = _descriptor.ServiceDescriptor(
  name='MonitorService',
  full_name='MonitorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=310,
  serialized_end=578,
  methods=[
  _descriptor.MethodDescriptor(
    name='fetchKnownStudents',
    full_name='MonitorService.fetchKnownStudents',
    index=0,
    containing_service=None,
    input_type=_EMPTYMESSAGE,
    output_type=_KNOWNSTUDENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='onStepDetected',
    full_name='MonitorService.onStepDetected',
    index=1,
    containing_service=None,
    input_type=_STEPDETECTIONMESSAGE,
    output_type=_MONITORRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='onProximityDetected',
    full_name='MonitorService.onProximityDetected',
    index=2,
    containing_service=None,
    input_type=_PROXIMITYMESSAGE,
    output_type=_MONITORRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='onMotionDetected',
    full_name='MonitorService.onMotionDetected',
    index=3,
    containing_service=None,
    input_type=_MOTIONDETECTIONMESSAGE,
    output_type=_MONITORRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MONITORSERVICE)

DESCRIPTOR.services_by_name['MonitorService'] = _MONITORSERVICE

# @@protoc_insertion_point(module_scope)
