# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitor.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\027mliot.monitor.generatedP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmonitor.proto\"U\n\x18StudentConnectionMessage\x12\x13\n\x0b\x63\x61rd_number\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x13\n\x0bport_number\x18\x03 \x01(\x05\">\n\x19StudentConnectionResponse\x12\x10\n\x08\x65xam_url\x18\x01 \x01(\t\x12\x0f\n\x07\x61pi_url\x18\x02 \x01(\t\"\x0e\n\x0c\x45mptyMessage\"i\n\x14KnownStudentResponse\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x13\n\x0b\x63\x61rd_number\x18\x03 \x01(\t\x12\x15\n\rprofile_photo\x18\x04 \x01(\x0c\"&\n\x0fMonitorResponse\x12\x13\n\x0bis_received\x18\x01 \x01(\x08\"/\n\x18MovementDetectionMessage\x12\x13\n\x0bis_detected\x18\x01 \x01(\x08\x32\xe4\x01\n\x0eMonitorService\x12>\n\x12\x66\x65tchKnownStudents\x12\r.EmptyMessage\x1a\x15.KnownStudentResponse\"\x00\x30\x01\x12M\n\x12onStudentConnected\x12\x19.StudentConnectionMessage\x1a\x1a.StudentConnectionResponse\"\x00\x12\x43\n\x12onMovementDetected\x12\x19.MovementDetectionMessage\x1a\x10.MonitorResponse\"\x00\x42\x1b\n\x17mliot.monitor.generatedP\x01\x62\x06proto3'
)




_STUDENTCONNECTIONMESSAGE = _descriptor.Descriptor(
  name='StudentConnectionMessage',
  full_name='StudentConnectionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='card_number', full_name='StudentConnectionMessage.card_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='StudentConnectionMessage.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port_number', full_name='StudentConnectionMessage.port_number', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=102,
)


_STUDENTCONNECTIONRESPONSE = _descriptor.Descriptor(
  name='StudentConnectionResponse',
  full_name='StudentConnectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exam_url', full_name='StudentConnectionResponse.exam_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='api_url', full_name='StudentConnectionResponse.api_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=166,
)


_EMPTYMESSAGE = _descriptor.Descriptor(
  name='EmptyMessage',
  full_name='EmptyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=182,
)


_KNOWNSTUDENTRESPONSE = _descriptor.Descriptor(
  name='KnownStudentResponse',
  full_name='KnownStudentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='KnownStudentResponse.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='KnownStudentResponse.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='card_number', full_name='KnownStudentResponse.card_number', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='profile_photo', full_name='KnownStudentResponse.profile_photo', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=289,
)


_MONITORRESPONSE = _descriptor.Descriptor(
  name='MonitorResponse',
  full_name='MonitorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_received', full_name='MonitorResponse.is_received', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=329,
)


_MOVEMENTDETECTIONMESSAGE = _descriptor.Descriptor(
  name='MovementDetectionMessage',
  full_name='MovementDetectionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_detected', full_name='MovementDetectionMessage.is_detected', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=378,
)

DESCRIPTOR.message_types_by_name['StudentConnectionMessage'] = _STUDENTCONNECTIONMESSAGE
DESCRIPTOR.message_types_by_name['StudentConnectionResponse'] = _STUDENTCONNECTIONRESPONSE
DESCRIPTOR.message_types_by_name['EmptyMessage'] = _EMPTYMESSAGE
DESCRIPTOR.message_types_by_name['KnownStudentResponse'] = _KNOWNSTUDENTRESPONSE
DESCRIPTOR.message_types_by_name['MonitorResponse'] = _MONITORRESPONSE
DESCRIPTOR.message_types_by_name['MovementDetectionMessage'] = _MOVEMENTDETECTIONMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StudentConnectionMessage = _reflection.GeneratedProtocolMessageType('StudentConnectionMessage', (_message.Message,), {
  'DESCRIPTOR' : _STUDENTCONNECTIONMESSAGE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:StudentConnectionMessage)
  })
_sym_db.RegisterMessage(StudentConnectionMessage)

StudentConnectionResponse = _reflection.GeneratedProtocolMessageType('StudentConnectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _STUDENTCONNECTIONRESPONSE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:StudentConnectionResponse)
  })
_sym_db.RegisterMessage(StudentConnectionResponse)

EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMessage)
  })
_sym_db.RegisterMessage(EmptyMessage)

KnownStudentResponse = _reflection.GeneratedProtocolMessageType('KnownStudentResponse', (_message.Message,), {
  'DESCRIPTOR' : _KNOWNSTUDENTRESPONSE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:KnownStudentResponse)
  })
_sym_db.RegisterMessage(KnownStudentResponse)

MonitorResponse = _reflection.GeneratedProtocolMessageType('MonitorResponse', (_message.Message,), {
  'DESCRIPTOR' : _MONITORRESPONSE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:MonitorResponse)
  })
_sym_db.RegisterMessage(MonitorResponse)

MovementDetectionMessage = _reflection.GeneratedProtocolMessageType('MovementDetectionMessage', (_message.Message,), {
  'DESCRIPTOR' : _MOVEMENTDETECTIONMESSAGE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:MovementDetectionMessage)
  })
_sym_db.RegisterMessage(MovementDetectionMessage)


DESCRIPTOR._options = None

_MONITORSERVICE = _descriptor.ServiceDescriptor(
  name='MonitorService',
  full_name='MonitorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=381,
  serialized_end=609,
  methods=[
  _descriptor.MethodDescriptor(
    name='fetchKnownStudents',
    full_name='MonitorService.fetchKnownStudents',
    index=0,
    containing_service=None,
    input_type=_EMPTYMESSAGE,
    output_type=_KNOWNSTUDENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='onStudentConnected',
    full_name='MonitorService.onStudentConnected',
    index=1,
    containing_service=None,
    input_type=_STUDENTCONNECTIONMESSAGE,
    output_type=_STUDENTCONNECTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='onMovementDetected',
    full_name='MonitorService.onMovementDetected',
    index=2,
    containing_service=None,
    input_type=_MOVEMENTDETECTIONMESSAGE,
    output_type=_MONITORRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MONITORSERVICE)

DESCRIPTOR.services_by_name['MonitorService'] = _MONITORSERVICE

# @@protoc_insertion_point(module_scope)
