# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sink_pb2 as sink__pb2


class SinkServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendAudio = channel.unary_unary(
                '/SinkService/SendAudio',
                request_serializer=sink__pb2.Audio.SerializeToString,
                response_deserializer=sink__pb2.Response.FromString,
                )
        self.SendVideo = channel.unary_unary(
                '/SinkService/SendVideo',
                request_serializer=sink__pb2.Video.SerializeToString,
                response_deserializer=sink__pb2.Response.FromString,
                )
        self.SendAcceleration = channel.unary_unary(
                '/SinkService/SendAcceleration',
                request_serializer=sink__pb2.Acceleration.SerializeToString,
                response_deserializer=sink__pb2.Response.FromString,
                )


class SinkServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAcceleration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SinkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAudio,
                    request_deserializer=sink__pb2.Audio.FromString,
                    response_serializer=sink__pb2.Response.SerializeToString,
            ),
            'SendVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.SendVideo,
                    request_deserializer=sink__pb2.Video.FromString,
                    response_serializer=sink__pb2.Response.SerializeToString,
            ),
            'SendAcceleration': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAcceleration,
                    request_deserializer=sink__pb2.Acceleration.FromString,
                    response_serializer=sink__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SinkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SinkService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SinkService/SendAudio',
            sink__pb2.Audio.SerializeToString,
            sink__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SinkService/SendVideo',
            sink__pb2.Video.SerializeToString,
            sink__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendAcceleration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SinkService/SendAcceleration',
            sink__pb2.Acceleration.SerializeToString,
            sink__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
